### ISSUE TITLE
TableFeatures request doesn't always need 'msg'

### ISSUE THREAD

**Issue by byllyfish** [byllyfish/oftr#7]
```python
>>> 'type: REQUEST.TABLE_FEATURES'.encode('openflow')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bfish/code/pylibofp/zof/codec.py", line 80, in _of_encode
    return encode(text), len(text)
  File "/Users/bfish/code/pylibofp/zof/codec.py", line 64, in encode
    opcode, text.encode('utf-8'), buflen=max(len(text), 1024))
  File "/Users/bfish/code/pylibofp/zof/codec.py", line 49, in _oftr_call
    raise CodecError(buf[:-result].decode('utf-8'))
zof.exception.CodecError: YAML:1:1: error: missing required key 'msg'
type: REQUEST.TABLE_FEATURES
^

```

vs.

```python
>>> 'type: REQUEST.TABLE_FEATURES\nmsg: '.encode('openflow')
b'\x04\x12\x00\x10\x00\x00\x00\x00\x00\x0c\x00\x00\x00\x00\x00\x00'

```

**Comment by byllyfish** [comment]
Fixed in version 0.39.
